#!/bin/sh
# flow-statistics agent installer (OpenWrt / ImmortalWrt)
# Target: aarch64/arm64 + Linux kernel >= 6.12
#
# Usage:
#   FS_TOKEN=<secret> wget -qO- https://dagongren.tech/public/flow-statistics/flow-statistics_install.sh | sh
#   or: FS_TOKEN=<secret> sh flow-statistics_install.sh
#
# Env overrides:
#   FS_BASE_URL   download root (default https://dagongren.tech/public/flow-statistics)
#   FS_SERVER     report URL
#   FS_TOKEN      X-Device-Token (required unless /etc/flow-statistics/agent.conf already has TOKEN)
#   FS_INTERVAL   sample interval (default 30s)
#   FS_ROUTER_ID  router_id (default: random, persisted)
#   FS_SKIP_HASH  set to 1 to skip sha256 check (not recommended)

set -e

FS_BASE_URL="${FS_BASE_URL:-https://dagongren.tech/public/flow-statistics}"
USER_SERVER="${FS_SERVER:-}"
USER_INTERVAL="${FS_INTERVAL:-}"
FS_SERVER="${FS_SERVER:-https://dagongren.tech/api/v1/traffic/report}"
FS_INTERVAL="${FS_INTERVAL:-30s}"

BIN_NAME="traffic-agent"
BIN_URL="${FS_BASE_URL}/traffic-agent-linux-arm64"
SHA_URL="${BIN_URL}.sha256"
INIT_NAME="flow-statistics"
BIN_PATH="/usr/sbin/${BIN_NAME}"
INIT_PATH="/etc/init.d/${INIT_NAME}"
CONF_DIR="/etc/flow-statistics"
CONF_FILE="${CONF_DIR}/agent.conf"
TMP_BIN="/tmp/${BIN_NAME}.$$"
TMP_SHA="/tmp/${BIN_NAME}.$$.sha256"

log() { echo "[flow-statistics] $*"; }
die() { echo "[flow-statistics] ERROR: $*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

shell_squote() {
  printf "'%s'" "$(printf "%s" "$1" | sed "s/'/'\\\\''/g")"
}

# --- arch ---
ARCH="$(uname -m 2>/dev/null || echo unknown)"
case "$ARCH" in
  aarch64|arm64) ;;
  *) die "arm64/aarch64 only, got: $ARCH" ;;
esac

# --- kernel >= 6.12 (published binary targets OpenWrt 24+ / ImmortalWrt) ---
KREL="$(uname -r 2>/dev/null || echo 0.0.0)"
KMAJ="${KREL%%.*}"
KREST="${KREL#*.}"
KMIN="${KREST%%.*}"
KMIN="${KMIN%%-*}"
KMIN="${KMIN%%.*}"
case "$KMAJ" in *[!0-9]*) KMAJ=0 ;; esac
case "$KMIN" in *[!0-9]*) KMIN=0 ;; esac
if [ "${KMAJ:-0}" -lt 6 ] || { [ "${KMAJ:-0}" -eq 6 ] && [ "${KMIN:-0}" -lt 12 ]; }; then
  die "need Linux kernel >= 6.12, got: $KREL"
fi
log "env OK: arch=$ARCH kernel=$KREL"

need_cmd iw
if command -v curl >/dev/null 2>&1; then
  DL="curl"
elif command -v wget >/dev/null 2>&1; then
  DL="wget"
elif command -v uclient-fetch >/dev/null 2>&1; then
  DL="uclient-fetch"
else
  die "need curl / wget / uclient-fetch"
fi

download() {
  # download <url> <out>
  _url="$1"
  _out="$2"
  case "$DL" in
    curl) curl -fsSL "$_url" -o "$_out" ;;
    wget) wget -qO "$_out" "$_url" ;;
    uclient-fetch) uclient-fetch -q -O "$_out" "$_url" ;;
  esac
}

EXISTING_TOKEN=""
EXISTING_ROUTER=""
EXISTING_SERVER=""
EXISTING_INTERVAL=""
if [ -f "$CONF_FILE" ]; then
  # shellcheck disable=SC1090
  . "$CONF_FILE"
  EXISTING_TOKEN="${TOKEN:-}"
  EXISTING_ROUTER="${ROUTER_ID:-}"
  EXISTING_SERVER="${SERVER_URL:-}"
  EXISTING_INTERVAL="${INTERVAL:-}"
  TOKEN=""
  ROUTER_ID=""
  SERVER_URL=""
  INTERVAL=""
fi

if [ -n "${FS_TOKEN:-}" ]; then
  TOKEN="$FS_TOKEN"
else
  TOKEN="$EXISTING_TOKEN"
fi
if [ -z "$TOKEN" ] || [ "$TOKEN" = "change-me-traffic-token" ]; then
  die "FS_TOKEN is required (installer no longer ships a shared production token)"
fi

if [ -n "${FS_ROUTER_ID:-}" ]; then
  ROUTER_ID="$FS_ROUTER_ID"
else
  ROUTER_ID="$EXISTING_ROUTER"
fi

rand_router_id() {
  if [ -r /dev/urandom ] && command -v tr >/dev/null 2>&1; then
    tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 10
    return
  fi
  echo "r$(date +%s | tail -c 7)$(awk 'BEGIN{srand(); printf "%03d", int(rand()*1000)}')"
}

mkdir -p "$CONF_DIR"
if [ -z "${ROUTER_ID:-}" ]; then
  ROUTER_ID="$(rand_router_id)"
  [ -n "$ROUTER_ID" ] || die "failed to generate ROUTER_ID"
  log "generated ROUTER_ID: $ROUTER_ID"
else
  log "using ROUTER_ID: $ROUTER_ID"
fi

if [ -n "$USER_SERVER" ]; then
  FS_SERVER="$USER_SERVER"
elif [ -n "$EXISTING_SERVER" ]; then
  FS_SERVER="$EXISTING_SERVER"
fi
if [ -n "$USER_INTERVAL" ]; then
  FS_INTERVAL="$USER_INTERVAL"
elif [ -n "$EXISTING_INTERVAL" ]; then
  FS_INTERVAL="$EXISTING_INTERVAL"
fi

# --- write conf (single-quoted values; sourced by init) ---
{
  echo "# generated by flow-statistics_install.sh"
  echo "SERVER_URL=$(shell_squote "$FS_SERVER")"
  echo "TOKEN=$(shell_squote "$TOKEN")"
  echo "ROUTER_ID=$(shell_squote "$ROUTER_ID")"
  echo "INTERVAL=$(shell_squote "$FS_INTERVAL")"
} >"$CONF_FILE"
chmod 600 "$CONF_FILE"

# --- download binary ---
log "download agent: $BIN_URL"
rm -f "$TMP_BIN" "$TMP_SHA"
download "$BIN_URL" "$TMP_BIN" || die "download failed: $BIN_URL"
chmod +x "$TMP_BIN"
if command -v file >/dev/null 2>&1; then
  file "$TMP_BIN" | grep -qi ELF || die "downloaded file is not ELF"
elif command -v head >/dev/null 2>&1; then
  _magic="$(hexdump -n 4 -e '1/1 "%02x"' "$TMP_BIN" 2>/dev/null || od -An -tx1 -N4 "$TMP_BIN" 2>/dev/null | tr -d ' \n')"
  echo "$_magic" | grep -qi '7f454c46' || log "warn: could not verify ELF magic, continuing"
fi

if [ "${FS_SKIP_HASH:-0}" = "1" ]; then
  log "warn: FS_SKIP_HASH=1, skipping sha256"
else
  if download "$SHA_URL" "$TMP_SHA"; then
    _expect="$(awk '{print $1; exit}' "$TMP_SHA" | tr 'A-F' 'a-f')"
    _got=""
    if command -v sha256sum >/dev/null 2>&1; then
      _got="$(sha256sum "$TMP_BIN" | awk '{print $1}')"
    elif command -v sha256 >/dev/null 2>&1; then
      _got="$(sha256 -q "$TMP_BIN" 2>/dev/null || sha256 "$TMP_BIN" | awk '{print $1}')"
    fi
    if [ -z "$_expect" ]; then
      die "empty hash in $SHA_URL"
    fi
    if [ -z "$_got" ]; then
      die "no sha256 tool on device; set FS_SKIP_HASH=1 to override"
    fi
    if [ "$_expect" != "$_got" ]; then
      die "sha256 mismatch: expected $_expect got $_got"
    fi
    log "sha256 OK"
  else
    die "sha256 file missing: $SHA_URL (set FS_SKIP_HASH=1 to override)"
  fi
fi
rm -f "$TMP_SHA"

# stop old service if present
if [ -x "$INIT_PATH" ]; then
  "$INIT_PATH" stop 2>/dev/null || true
fi

mv -f "$TMP_BIN" "$BIN_PATH"
chmod 755 "$BIN_PATH"

# --- procd init script: token via env, never argv ---
cat >"$INIT_PATH" <<'INITEOF'
#!/bin/sh /etc/rc.common
# flow-statistics traffic agent

START=99
STOP=10
USE_PROCD=1
NAME=flow-statistics
PROG=/usr/sbin/traffic-agent
CONF=/etc/flow-statistics/agent.conf

load_conf() {
	SERVER_URL="https://dagongren.tech/api/v1/traffic/report"
	TOKEN=""
	ROUTER_ID="main-router-01"
	INTERVAL="30s"
	[ -f "$CONF" ] && . "$CONF"
}

start_service() {
	load_conf
	[ -n "$TOKEN" ] || {
		echo "flow-statistics: TOKEN missing in $CONF" >&2
		return 1
	}
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param env \
		"TRAFFIC_SERVER=$SERVER_URL" \
		"TRAFFIC_TOKEN=$TOKEN" \
		"TRAFFIC_ROUTER_ID=$ROUTER_ID" \
		"TRAFFIC_INTERVAL=$INTERVAL"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
INITEOF
chmod 755 "$INIT_PATH"

if "$INIT_PATH" enable 2>/dev/null; then
  :
else
  log "enable returned non-zero, trying start anyway"
fi
"$INIT_PATH" restart 2>/dev/null || "$INIT_PATH" start || die "failed to start service"

sleep 1
if pidof "$BIN_NAME" >/dev/null 2>&1 || pgrep -f "$BIN_PATH" >/dev/null 2>&1; then
  log "service running"
else
  log "warn: process not seen, check: logread | grep traffic-agent"
fi

echo
echo "=========================================="
echo " flow-statistics installed"
echo " ROUTER_ID = ${ROUTER_ID}"
echo " binary    = ${BIN_PATH}"
echo " config    = ${CONF_FILE}"
echo " service   = ${INIT_PATH} {start|stop|restart}"
echo " use ROUTER_ID above on the dashboard"
echo "=========================================="
echo "ROUTER_ID=${ROUTER_ID}"
