#!/bin/sh
# flow-statistics agent installer (OpenWrt / ImmortalWrt)
# 仅适配: aarch64/arm64 + Linux kernel >= 6.12
#
# 用法:
#   wget -qO- https://dagongren.tech/public/flow-statistics/flow-statistics_install.sh | sh
#   或: sh flow-statistics_install.sh
#
# 环境变量可覆盖:
#   FS_BASE_URL   下载根目录 (默认 https://dagongren.tech/public/flow-statistics)
#   FS_SERVER     上报 URL
#   FS_TOKEN      X-Device-Token
#   FS_INTERVAL   采样间隔 (默认 30s)
#   FS_ROUTER_ID  指定 router_id (默认安装时随机生成并持久化)

set -e

FS_BASE_URL="${FS_BASE_URL:-https://dagongren.tech/public/flow-statistics}"
FS_SERVER="${FS_SERVER:-https://dagongren.tech/api/v1/traffic/report}"
FS_TOKEN="${FS_TOKEN:-dd16d55a075f1429067e86be1a0b576c}"
FS_INTERVAL="${FS_INTERVAL:-30s}"

BIN_NAME="traffic-agent"
BIN_URL="${FS_BASE_URL}/traffic-agent-linux-arm64"
INIT_NAME="flow-statistics"
BIN_PATH="/usr/sbin/${BIN_NAME}"
INIT_PATH="/etc/init.d/${INIT_NAME}"
CONF_DIR="/etc/flow-statistics"
CONF_FILE="${CONF_DIR}/agent.conf"
TMP_BIN="/tmp/${BIN_NAME}.$$"

log() { echo "[flow-statistics] $*"; }
die() { echo "[flow-statistics] ERROR: $*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "缺少命令: $1"
}

# --- arch ---
ARCH="$(uname -m 2>/dev/null || echo unknown)"
case "$ARCH" in
  aarch64|arm64) ;;
  *) die "仅支持 arm64/aarch64，当前: $ARCH" ;;
esac

# --- kernel >= 6.12 ---
KREL="$(uname -r 2>/dev/null || echo 0.0.0)"
KMAJ="${KREL%%.*}"
KREST="${KREL#*.}"
KMIN="${KREST%%.*}"
KMIN="${KMIN%%-*}"
KMIN="${KMIN%%.*}"
case "$KMAJ" in *[!0-9]*) KMAJ=0 ;; esac
case "$KMIN" in *[!0-9]*) KMIN=0 ;; esac
if [ "${KMAJ:-0}" -lt 6 ] || { [ "${KMAJ:-0}" -eq 6 ] && [ "${KMIN:-0}" -lt 12 ]; }; then
  die "需要 Linux 内核 >= 6.12，当前: $KREL"
fi
log "环境 OK: arch=$ARCH kernel=$KREL"

need_cmd iw
if command -v curl >/dev/null 2>&1; then
  DL="curl"
elif command -v wget >/dev/null 2>&1; then
  DL="wget"
elif command -v uclient-fetch >/dev/null 2>&1; then
  DL="uclient-fetch"
else
  die "需要 curl / wget / uclient-fetch 之一"
fi

download() {
  # download <url> <out>
  _url="$1"
  _out="$2"
  case "$DL" in
    curl) curl -fsSL "$_url" -o "$_out" ;;
    wget) wget -qO "$_out" "$_url" ;;
    uclient-fetch) uclient-fetch -q -O "$_out" "$_url" ;;
  esac
}

# --- router_id: keep existing, or env, or random ---
rand_router_id() {
  # 10 chars A-Za-z0-9
  if [ -r /dev/urandom ] && command -v tr >/dev/null 2>&1; then
    tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 10
    return
  fi
  # fallback
  echo "r$(date +%s | tail -c 7)$(awk 'BEGIN{srand(); printf "%03d", int(rand()*1000)}')"
}

mkdir -p "$CONF_DIR"
if [ -n "${FS_ROUTER_ID:-}" ]; then
  ROUTER_ID="$FS_ROUTER_ID"
elif [ -f "$CONF_FILE" ]; then
  # shellcheck disable=SC1090
  . "$CONF_FILE"
  ROUTER_ID="${ROUTER_ID:-}"
fi
if [ -z "${ROUTER_ID:-}" ]; then
  ROUTER_ID="$(rand_router_id)"
  [ -n "$ROUTER_ID" ] || die "生成 ROUTER_ID 失败"
  log "生成新 ROUTER_ID: $ROUTER_ID"
else
  log "使用 ROUTER_ID: $ROUTER_ID"
fi

# --- write conf ---
cat >"$CONF_FILE" <<EOF
# generated by flow-statistics_install.sh
SERVER_URL="${FS_SERVER}"
TOKEN="${FS_TOKEN}"
ROUTER_ID="${ROUTER_ID}"
INTERVAL="${FS_INTERVAL}"
EOF
chmod 600 "$CONF_FILE"

# --- download binary ---
log "下载 agent: $BIN_URL"
rm -f "$TMP_BIN"
download "$BIN_URL" "$TMP_BIN" || die "下载失败: $BIN_URL"
chmod +x "$TMP_BIN"
# quick sanity: ELF
if command -v file >/dev/null 2>&1; then
  file "$TMP_BIN" | grep -qi ELF || die "下载的不是可执行文件"
elif command -v head >/dev/null 2>&1; then
  # ELF magic
  _magic="$(hexdump -n 4 -e '1/1 "%02x"' "$TMP_BIN" 2>/dev/null || od -An -tx1 -N4 "$TMP_BIN" 2>/dev/null | tr -d ' \n')"
  echo "$_magic" | grep -qi '7f454c46' || log "警告: 无法校验 ELF 魔数，继续安装"
fi

# stop old service if present
if [ -x "$INIT_PATH" ]; then
  "$INIT_PATH" stop 2>/dev/null || true
fi

mv -f "$TMP_BIN" "$BIN_PATH"
chmod 755 "$BIN_PATH"

# --- procd init script ---
cat >"$INIT_PATH" <<'INITEOF'
#!/bin/sh /etc/rc.common
# flow-statistics traffic agent

START=99
STOP=10
USE_PROCD=1
NAME=flow-statistics
PROG=/usr/sbin/traffic-agent
CONF=/etc/flow-statistics/agent.conf

load_conf() {
	SERVER_URL="https://dagongren.tech/api/v1/traffic/report"
	TOKEN="change-me-traffic-token"
	ROUTER_ID="main-router-01"
	INTERVAL="30s"
	[ -f "$CONF" ] && . "$CONF"
}

start_service() {
	load_conf
	procd_open_instance
	procd_set_param command "$PROG" \
		-server "$SERVER_URL" \
		-token "$TOKEN" \
		-router-id "$ROUTER_ID" \
		-interval "$INTERVAL"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "network"
}

reload_service() {
	stop
	start
}
INITEOF
chmod 755 "$INIT_PATH"

# enable + start
if "$INIT_PATH" enable 2>/dev/null; then
  :
else
  # some builds use differently
  log "enable 返回非 0，尝试继续 start"
fi
"$INIT_PATH" restart 2>/dev/null || "$INIT_PATH" start || die "启动服务失败"

sleep 1
if pidof "$BIN_NAME" >/dev/null 2>&1 || pgrep -f "$BIN_PATH" >/dev/null 2>&1; then
  log "服务已运行"
else
  log "警告: 未检测到进程，请检查: logread | grep traffic-agent"
fi

echo
echo "=========================================="
echo " flow-statistics 安装完成"
echo " ROUTER_ID = ${ROUTER_ID}"
echo " 二进制    = ${BIN_PATH}"
echo " 配置      = ${CONF_FILE}"
echo " 服务      = ${INIT_PATH} {start|stop|restart}"
echo " 大屏查询时请填写上述 ROUTER_ID"
echo "=========================================="
echo "ROUTER_ID=${ROUTER_ID}"
